#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : padatious
Version  : 0.4.6
Release  : 3
URL      : https://files.pythonhosted.org/packages/1f/37/0022764d88b1aacb7f42a9e3ba5250b10212d8b6cf6223c58e639d669a6c/padatious-0.4.6.tar.gz
Source0  : https://files.pythonhosted.org/packages/1f/37/0022764d88b1aacb7f42a9e3ba5250b10212d8b6cf6223c58e639d669a6c/padatious-0.4.6.tar.gz
Summary  : A neural network intent parser
Group    : Development/Tools
License  : Apache-2.0
Requires: padatious-python = %{version}-%{release}
Requires: padatious-python3 = %{version}-%{release}
Requires: fann2
Requires: padaos
BuildRequires : buildreq-distutils3

%description
# Padatious #
An efficient and agile neural network intent parser
### Features ###

%package python
Summary: python components for the padatious package.
Group: Default
Requires: padatious-python3 = %{version}-%{release}

%description python
python components for the padatious package.


%package python3
Summary: python3 components for the padatious package.
Group: Default
Requires: python3-core

%description python3
python3 components for the padatious package.


%prep
%setup -q -n padatious-0.4.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1549030224
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
